label: 'Označení nálezu'
description: 'Zvolte označení vhodné pro popis nálezu jako celku. Formát označení není určen, lze jej konstruovat libovolně, měl by však být v rámci dané instituce jedinečný.'
