label: Obec
description: 'Zadává se oficiální název obce, na jejímž katastru se archeologické naleziště nachází; v případě, že archeologické naleziště přesahuje katastr jedné obce, zapište jednu vybranou obec.'
