label: Organizace
description: "Zvolte svou dodavatelskou organizaci pomocí tlačítka <strong>Přidat existující</strong>; pokud ještě není v\_systému zavedena, použijte tlačítko <strong>Přidat nový</strong>."
