label: 'Osobní kontakty'
description: "Zvolte osobu zastupující instituci pomocí tlačítka <strong>Přidat existující</strong>; pokud ještě není v\_systému zavedena, použijte tlačítko <strong>Přidat nový</strong>."
