label: 'Kód obce'
description: "Kódy českých míst jsou dostupné na \r\n https://vdp.cuzk.cz/vdp/ruian/obce/, kódy slovenských míst jsou dostupné na https://www.epi.sk/disk/zz/file/2002/2002c230z0597p01t003ga.pdf."
