label: 'Souhlas s provedením destruktivních analýz'
settings:
  on_label: Ano
  off_label: Ne
description: "Vyjádřete souhlas či nesouhlas s\_tím, že při provádění analýz může být narušena kompaktnost artefaktu."
