display:
  default:
    display_options:
      fields:
        field_analysis_type:
          label: Analýza
        field_instrument:
          label: Přístroj
        field_analysed_by:
          label: Výzkumník
        field_date_analysed:
          label: 'Datum analýzy'
  entity_view_2:
    display_options:
      fields:
        nothing:
          alter:
            text: '{{ field_artefact_category|capitalize }} ({{ field_artefact_id }}) » vzorek {{ field_sample_id }}'
