display:
  default:
    display_title: Výchozí
    display_options:
      fields:
        name:
          label: 'Uživatelské jméno'
        status:
          label: Stav
        operations:
          label: Operace
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Vše -'
      exposed_form:
        options:
          exposed_sorts_label: 'Řadit dle'
      filters:
        status:
          group_info:
            label: Stav
