display:
  default:
    display_options:
      fields:
        nid:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        nid_2:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        view:
          label: Obrázek
        name:
          label: Analýza
        nothing:
          label: 'Analyzovaná keramika'
        name_7:
          label: Lokalita
        from_1:
          format_plural_string: !!binary AwM=
        to_1:
          format_plural_string: !!binary AwM=
        nothing_1:
          label: Datace
      exposed_form:
        options:
          submit_button: Odeslat
          reset_button_label: Resetovat
          exposed_sorts_label: 'Řadit podle'
          sort_asc_label: vzestupně
          sort_desc_label: sestupně
      filters:
        facets_field_artefact_category:
          expose:
            label: 'Kategorie artefaktu'
        facets_field_analysis_type:
          expose:
            label: 'Typ analýzy'
        facets_field_instrument:
          expose:
            label: Přístroj
        to:
          expose:
            label: 'Horní odhad teploty výpalu'
        from:
          expose:
            label: 'Spodní odhad teploty výpalu'
        field_porosity:
          expose:
            label: 'Spodní odhad pórovitosti [%]'
        field_porosity_1:
          expose:
            label: 'Horní odhad pórovitosti [%]'
        facets_name_8:
          expose:
            label: 'Fragmenty minerálů a hornin'
        facets_field_microstructure:
          expose:
            label: Mikrostruktura
        facets_field_grain_type:
          expose:
            label: Zrnitost
        facets_field_binder_type:
          expose:
            label: 'Typ pojiva'
      header:
        result:
          content: 'Zobrazují se položky @start - @end z @total'
      sorts:
        name:
          expose:
            label: 'Typ analýzy'
        name_5:
          expose:
            label: 'Kategorie artefaktu'
        field_artefact_id:
          expose:
            label: 'ID artefaktu'
        from:
          expose:
            label: 'Teplota výpalu » spodní odhad'
        to:
          expose:
            label: 'Teplota výpalu » horní odhad'
        from_1:
          expose:
            label: 'Datace » spodní odhad'
        to_1:
          expose:
            label: 'Datace » horní odhad'
      pager:
        options:
          tags:
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Počet položek na stránku'
            items_per_page_options_all_label: '- Vše -'
      title: 'Vyhledávání v analýzách'
  page_1:
    display_options:
      menu:
        title: Analýzy
