display:
  entity_browser_4:
    display_options:
      fields:
        field_city:
          label: Obec
        field_city_code:
          label: 'Kód obce'
      exposed_form:
        options:
          submit_button: Vyhledat
      filters:
        name:
          expose:
            label: Název
      header:
        area:
          content:
            value: '<p>Vyberte (kliknutím na přepínač) jednu položku ze seznamu, ve kterém lze vyhledávat zápisem znaků v&nbsp;poli <strong>Název</strong>; volbu potvrďte tlačítkem <strong>Vybrat</strong> na konci interaktivního formuláře. Pokud hledaná položka neexistuje, vraťte se o dva kroky zpět a použijte volbu <strong>Přidat nový</strong>.&nbsp;</p>'
            format: basic_html
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Použít
  entity_browser_2:
    display_options:
      exposed_form:
        options:
          submit_button: Vyhledat
      filters:
        name:
          expose:
            label: Název
      fields:
        field_coll_contacts:
          label: Kontakt
        field_contact_email:
          label: 'Kontaktní e-mail'
      header:
        area:
          content:
            value: '<p>Vyberte (kliknutím na přepínač) jednu položku ze seznamu, ve kterém lze vyhledávat zápisem znaků v&nbsp;poli <strong>Název</strong>; volbu potvrďte tlačítkem <strong>Vybrat</strong> na konci interaktivního formuláře. Pokud hledaná položka neexistuje, vraťte se o dva kroky zpět a použijte volbu <strong>Přidat nový</strong>.</p>'
            format: basic_html
  entity_browser_3:
    display_options:
      exposed_form:
        options:
          submit_button: Vyhledat
      filters:
        name:
          expose:
            label: Název
      fields:
        field_coll_contacts:
          label: Kontakt
        field_contact_email:
          label: 'Kontaktní e-mail'
      header:
        area:
          content:
            value: '<p>Zaškrtněte jednu nebo více položek ze seznamu, ve kterém lze vyhledávat zápisem znaků v&nbsp;poli <strong>Název</strong>; volbu potvrďte tlačítkem <strong>Vybrat</strong> na konci interaktivního formuláře. Pokud hledaná položka neexistuje, vraťte se o dva kroky zpět a použijte volbu <strong>Přidat nový</strong>.&nbsp;</p>'
            format: basic_html
