status: 1
pattern: '[node:field_artefact_category:0:entity] ([node:field_artefact_id:value])'
escape: false
preserve_titles: false
save: true
chunk: 50
dependencies:
  config:
    - node.type.a3d_object
new_content_behavior: 1
